wingers <- data.frame(
  player = c("Lionel Messi",
             "Mohamed Salah",
             "Kylian Mbappé",
             "Raheem Sterling",
             "Neymar Jr.",
             "Riyad Mahrez",
             "Sadio Mané",
             "Son Heung-min",
             "Lorenzo Insigne",
             "Jadon Sancho",
             "Federico Chiesa",
             "Vinícius Jr.",
             "Ángel di María",
             "Diogo Jota",
             "Leroy Sané",
             "Marcus Rashford",
             "Marco Reus",
             "Domenico Berardi",
             "Serge Gnabry",
             "Dušan Tadić"),
  npxG = c(0.52,
           0.58,
           0.57,
           0.47,
           0.34,
           0.35,
           0.49,
           0.31,
           0.23,
           0.22,
           0.31,
           0.39,
           0.26,
           0.65,
           0.43,
           0.24,
           0.36,
           0.32,
           0.45,
           0.41),
  total_shots = c(4.61,
                  3.92,
                  3.67,
                  2.71,
                  2.72,
                  3.08,
                  2.89,
                  2.29,
                  3.72,
                  1.38,
                  3.03,
                  2.61,
                  2.79,
                  3.55,
                  3.91,
                  2.55,
                  2.09,
                  3.75,
                  3.23,
                  2.40),
  league = c("La Liga",
             "Premier League",
             "Ligue 1",
             "Premier League",
             "Ligue 1",
             "Premier League",
             "Premier League",
             "Premier League",
             "Serie A",
             "Premier League",
             "Serie A",
             "La Liga",
             "Ligue 1",
             "Premier League",
             "Bundesliga",
             "Premier League",
             "Bundesliga",
             "Serie A",
             "Bundesliga",
             "Eredivisie"),
  xA = c(0.35,
         0.26,
         0.28,
         0.2,
         0.37,
         0.21,
         0.15,
         0.31,
         0.28,
         0.26,
         0.15,
         0.2,
         0.36,
         0.16,
         0.25,
         0.15,
         0.19,
         0.23,
         0.32,
         0.55),
  shot_creating = c(6.24,
                    4.08,
                    4.15,
                    3.39,
                    5.93,
                    4.24,
                    3.3,
                    3.82,
                    5.19,
                    4.62,
                    3.71,
                    4.84,
                    5.06,
                    3.29,
                    4.58,
                    3.25,
                    3.36,
                    4.52,
                    5.13,
                    6.60),
  dribbles = c(3.84,
               1.86,
               3.02,
               2.10,
               3.99,
               1.78,
               1.85,
               1.31,
               1.64,
               2.72,
               1.82,
               3.4,
               2.23,
               1.5,
               3.02,
               2.28,
               1.35,
               1.02,
               2.63,
               1.30),
  pass_completion = c(83.4,
                      79.6,
                      78.7,
                      84.5,
                      78.4,
                      83.3,
                      75.5,
                      76.7,
                      79.1,
                      82.6,
                      76.6,
                      83.5,
                      73.9,
                      70.8,
                      82.2,
                      77.8,
                      80.7,
                      72.6,
                      78.3,
                      69.0)
  )
wingers2 <- data.frame(
  player = c("Lionel Messi",
             "Mohamed Salah",
             "Kylian Mbappé",
             "Raheem Sterling",
             "Neymar Jr.",
             "Riyad Mahrez",
             "Sadio Mané",
             "Son Heung-min",
             "Lorenzo Insigne",
             "Jadon Sancho",
             "Federico Chiesa",
             "Vinícius Jr.",
             "Ángel di María",
             "",
             "Leroy Sané",
             "",
             "Marco Reus",
             "Domenico Berardi",
             "Serge Gnabry",
             "Dušan Tadić"),
  npxG = c(0.52,
           0.58,
           0.57,
           0.47,
           0.34,
           0.35,
           0.49,
           0.31,
           0.23,
           0.22,
           0.31,
           0.39,
           0.26,
           0.65,
           0.43,
           0.24,
           0.36,
           0.32,
           0.45,
           0.41),
  total_shots = c(4.61,
                  3.92,
                  3.67,
                  2.71,
                  2.72,
                  3.08,
                  2.89,
                  2.29,
                  3.72,
                  1.38,
                  3.03,
                  2.61,
                  2.79,
                  3.55,
                  3.91,
                  2.55,
                  2.09,
                  3.75,
                  3.23,
                  2.40),
  league = c("La Liga",
             "Premier League",
             "Ligue 1",
             "Premier League",
             "Ligue 1",
             "Premier League",
             "Premier League",
             "Premier League",
             "Serie A",
             "Premier League",
             "Serie A",
             "La Liga",
             "Ligue 1",
             "Premier League",
             "Bundesliga",
             "Premier League",
             "Bundesliga",
             "Serie A",
             "Bundesliga",
             "Eredivisie"),
  xA = c(0.35,
         0.26,
         0.28,
         0.2,
         0.37,
         0.21,
         0.15,
         0.31,
         0.28,
         0.26,
         0.15,
         0.2,
         0.36,
         0.16,
         0.25,
         0.15,
         0.19,
         0.23,
         0.32,
         0.55),
  shot_creating = c(6.24,
                    4.08,
                    4.15,
                    3.39,
                    5.93,
                    4.24,
                    3.3,
                    3.82,
                    5.19,
                    4.62,
                    3.71,
                    4.84,
                    5.06,
                    3.29,
                    4.58,
                    3.25,
                    3.36,
                    4.52,
                    5.13,
                    6.60),
  dribbles = c(3.84,
               1.86,
               3.02,
               2.10,
               3.99,
               1.78,
               1.85,
               1.31,
               1.64,
               2.72,
               1.82,
               3.4,
               2.23,
               1.5,
               3.02,
               2.28,
               1.35,
               1.02,
               2.63,
               1.30),
  pass_completion = c(83.4,
                      79.6,
                      78.7,
                      84.5,
                      78.4,
                      83.3,
                      75.5,
                      76.7,
                      79.1,
                      82.6,
                      76.6,
                      83.5,
                      73.9,
                      70.8,
                      82.2,
                      77.8,
                      80.7,
                      72.6,
                      78.3,
                      69.0)
)
strikers <- data.frame(
  player = c('Robert Lewandowski',
             'Cristiano Ronaldo',
             'Karim Benzema',
             'Kylian Mbappé',
             'Erling Haaland',
             'Romelu Lukaku',
             'Luis Suárez',
             'Lautaro Martínez',
             'Harry Kane',
             'Gerard Moreno',
             'Pierre-Emerick Aubameyang',
             'Jamie Vardy',
             'Zlatan Ibrahimović',
             'Ciro Immobile',
             'André Silva',
             'Dušan Vlahović',
             'Jonathan David',
             'Duván Zapata',
             'Patrik Schick',
             'Sébastien Haller'),
  npxG = c(1.02,
           0.61,
           0.53,
           0.57,
           0.71,
           0.39,
           0.37,
           0.45,
           0.56,
           0.44,
           0.41,
           0.34,
           0.54,
           0.49,
           0.53,
           0.37,
           0.35,
           0.58,
           0.63,
           1.33),
  total_shots = c(4.89,
                  4.44,
                  3.90,
                  3.67,
                  3.67,
                  2.39,
                  2.56,
                  3.74,
                  3.83,
                  3.11,
                  2.67,
                  2.24,
                  4.16,
                  3.48,
                  3.01,
                  2.98,
                  1.87,
                  3.90,
                  3.46,
                  3.33),
  league = c("Bundesliga",
             "Premier League",
             "La Liga",
             "Ligue 1",
             "Bundesliga",
             "Premier League",
             "La Liga",
             "Serie A",
             "Premier League",
             "La Liga",
             "Premier League",
             "Premier League",
             "Serie A",
             "Serie A",
             "Bundesliga",
             "Serie A",
             "Ligue 1",
             "Serie A",
             "Bundesliga",
             "Eredivisie"))

mycols1  <- c("darkblue","darkgoldenrod1","deepskyblue","forestgreen","brown",
              "chocolate1")
cols2 <- c("darkblue","darkgoldenrod1","deepskyblue","forestgreen","brown",
           "chocolate1", "coral2", "chartreuse2", "gold1", "blueviolet",
           "aquamarine4", "cyan3","deeppink", "darkorange2", "firebrick1",
           "khaki4", "seagreen3", "hotpink", "orchid1", "slateblue3")
library(ggplot2)

wingers1 <- ggplot(data = wingers,
                   mapping = aes(
                     x=total_shots,
                     y=npxG,
                     color = league,
                     label = player
                   ))+
  geom_point(size=5) +
  geom_text(hjust=0.5, vjust=2.25, size=3, colour="Black") +
  scale_color_manual(values=mycols1) +
  ggtitle("npxG vs. Total shots - Wingers") +
  xlab("Total Shots per 90") +
  ylab("Non-penalty expected goals (npxG) per 90")

wingers2 <- ggplot(data = wingers2,
                   mapping = aes(
                     x=shot_creating,
                     y=xA,
                     color = league,
                     label = player
                   ))+
  geom_point(size=5) +
  geom_text(hjust=0.75, vjust=2.5, size=3, colour="Black") +
  scale_color_manual(values=mycols1) +
  ggtitle("Expected Assists (xA) vs. Shot-creating actions - Wingers") +
  xlab("Shot-creating actions per 90") +
  ylab("Expected Assists (xA) per 90")

wingers3 <- ggplot(data = wingers,
                   mapping = aes(
                     x=dribbles,
                     y=pass_completion,
                     color = league,
                     label = player
                   ))+
  geom_point(size=5) +
  geom_text(hjust=0.5, vjust=2.25, size=3, colour="Black") +
  scale_color_manual(values=mycols1) +
  ggtitle("Pass completion % vs. Dribbles completed - Wingers") +
  xlab("Dribbles Completed per 90") +
  ylab("Pass Completion % per 90")

strikers1  <- ggplot(data = strikers,
                     mapping = aes(
                       x=total_shots,
                       y=npxG,
                       color = league,
                       label = player
                     ))+
  geom_point(size=5) +
  geom_text(hjust=0.5, vjust=2.25, size=3, colour="Black") +
  scale_color_manual(values=mycols1)+
  ggtitle("npxG vs. Total shots - Strikers") +
  xlab("Total Shots per 90") +
  ylab("Non-penalty expected goals (npxG) per 90")

# library(RColorBrewer)
# 
# qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
# col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
# mycols2 <- sample(col_vector,20)
# pie(rep(1,20), col=cols2)


